import { Inter } from "next/font/google";
import "./globals.css";
import HeadSection from "@/components/HeadSection";
import Footer from "@/components/Footer";
import Servey from "@/components/Servey";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shop Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <HeadSection />
        {children}
        <Servey />
        <Footer />
      </body>
    </html>
  );
}
